### ISSUE TITLE
PaperLib

### ISSUE THREAD

**Issue by XboxBedrock** [yyrichy/VanillaTerra#3]
Use paperlib instead of the paper API to be able to support spigot

**Comment by vaporrrr** [comment]
Not familiar with paperlib, but it appears it really only does chunk things so not really helpful for spigot compatibility. I really only use adventure and i can just shade then use spigot api

**Comment by vaporrrr** [comment]
I think ill just keep it the way it is

**Comment by XboxBedrock** [comment]
I use adventure with spigot with their bukkit  compat layer and uh i mean paperlib for teleportAsync
